### ISSUE TITLE
Hey, i saw you added a PR to the original feroxrev's version of the Pokemon Go API. We took over the work and restarted the project here: https://github.com/Vulnova/Vulnova. Feel free to contribute. Thanks :)

### ISSUE THREAD

**Issue by Degix** [martin-podlubny/hack-cam-2016#7]

**Comment by martin-podlubny** [comment]
Nah. Unless you guys propose some significantly new direction for the project, I am choosing to contribute my efforts to the original repo rather than fragment out into yet another tool. 

Also damn weird way to contact me :D
